# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyinfo',
            fields=[
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hireinfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('salary_max', models.CharField(max_length=10)),
                ('salary_min', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('job_require', models.CharField(max_length=1024)),
                ('job_require_keyword', models.CharField(max_length=100)),
                ('job_require_skill', models.CharField(max_length=100)),
            ],
        ),
    ]
