# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hireinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('jobname', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('salary_max', models.CharField(max_length=100)),
                ('salary_min', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=100)),
                ('job_require', models.CharField(max_length=1024)),
            ],
        ),
    ]
