# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180411_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyinfo',
            fields=[
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='hireinfo',
            name='company_size',
        ),
    ]
