# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180504_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireinfo',
            old_name='jobname',
            new_name='job_name',
        ),
        migrations.AddField(
            model_name='hireinfo',
            name='job_require_keyword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hireinfo',
            name='job_require_skill',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
